apiVersion: v1
kind: ConfigMap
metadata:
  name: beatzy-config
  namespace: beatzy
data:
  NODE_ENV: production
  PORT: "3000"
  ML_SERVICE_URL: http://ml-service:8000
  FRONTEND_URL: https://beatzy.app
  AWS_REGION: us-east-1
  ALLOWED_ORIGINS: https://beatzy.app,https://api.beatzy.app
